### ISSUE TITLE
TG проверка баланса на момент покупки услуги

### ISSUE THREAD

**Issue by FeliksMarello** [danuk/shm#10]
На данный момент при покупки услуги мы выдаем только 1 сообщение без всяких уведомлений. 
Было бы неплохо сделать проверку, которая будет проверять достаточно ли денег на балансе у клиента. 
Если не достаточно, то выводить 1 сообщение и к примеру переводить на форму оплаты, если достаточно, то выдавать услугу и другое сообщение.

**Comment by danuk** [comment]
Сделано.

Используйте `cb_not_enough_money`, подробнее здесь:

https://docs.myshm.ru/docs/setup/templates/telegram_bot/#%D0%B2%D1%81%D1%82%D1%80%D0%BE%D0%B5%D0%BD%D0%BD%D1%8B%D0%B5-%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D1%8B-shm
