### ISSUE TITLE
При создании услуги сроком 1 месяц expire выставляется как 1 год и 1 месяц

### ISSUE THREAD

**Issue by BarinVPN** [danuk/shm#15]
Система расчётов - honest
Создается услуга на 1 месяц, период равен 1
При этом expire у услуги 1 год и 1 месяц
![photo_2023-11-19_12-08-53](https://github.com/danuk/shm/assets/150382923/0b36eb99-6d3e-4da2-8d90-9c962a6cd155)
![photo_2023-11-19_12-10-54](https://github.com/danuk/shm/assets/150382923/ea93d5dd-2c8a-4b90-83a3-318ba7fe41df)

**Comment by danuk** [comment]
исправлено
