### ISSUE TITLE
Некорректный срок и стоимость услуги при продлении

### ISSUE THREAD

**Issue by BarinVPN** [danuk/shm#16]
При пролонгации услуги стоимостью 0 рублей и периодом действия 0.02 должна была подключиться услуга стоимость 1200 рублей и сроком действия 12 месяцев (выставлена как следующая)
По факту услуга подключилась, но за 100 рублей и сроком действия 1 месяц 🤯

Скриншоты:
Услуга 1 (бесплатная)
Услуга 2 (платная)
Пользовательская услуга (что получилось в результате)
![photo_2023-11-20_14-02-11](https://github.com/danuk/shm/assets/150382923/bf9acd73-530d-48e5-b0ef-c6ba1ae7a97e)
![photo_2023-11-20_14-02-11 (2)](https://github.com/danuk/shm/assets/150382923/f42d1ffc-1f53-4c63-b26c-39b548f80ec9)
![photo_2023-11-20_14-02-11 (3)](https://github.com/danuk/shm/assets/150382923/361bca6d-de78-4e2c-91f8-04c1dc3c233a)

**Comment by danuk** [comment]
исправлено
