### ISSUE TITLE
YooKassa Pay Error 503

### ISSUE THREAD

**Issue by websmithcode** [danuk/shm#17]
После полной настройки, вроде все завелось.
Но при попытке любым способом провести оплату через YooKassa - имеем следующую проблему:

URL: https://vpn.example.ru/shm/pay_systems/yookassa.cgi
Request: `action=create&amount=190`
```
HTTP/2 503 
server: nginx
date: Tue, 26 Dec 2023 03:50:26 GMT
content-type: application/json; charset=utf8
access-control-allow-credentials: true
access-control-allow-origin: https://billing.example.ru
X-Firefox-Spdy: h2
```
Response:
```
{
  "type": "error",
  "id": "b7603c01-c041-43af-91d0-248663d9d4f0",
  "code": "invalid_request",
  "description": "Invalid parameter's value (for example, the value is illegal or its format is incorrect). Send the value in accordance with the documentation.",
  "parameter": "receipt.items.payment_subject"
}
```

Настройки -> Конфигурация -> pay_systems -> value:
```
{
   "manual":{
      "name":"Платеж",
      "show_for_client":false
   },
   "yookassa":{
      "account_id":***,
      "api_key":"***",
      "customer_email":"***@ya.ru",
      "description":"VPN",
      "name":"ЮКасса",
      "return_url":"https://example.ru/success",
      "show_for_client":true,
      "template_id":"yookassa_template"
   }
}
```

**Comment by danuk** [comment]
Вижу ответ:
  "description": "Invalid parameter's value (for example, the value is illegal or its format is incorrect). Send the value in accordance with the documentation.",

Видимо нельзя использовать  "description":"VPN". 
Попробуйте в description написать что-то более существенное и на русском.
