### ISSUE TITLE
Не запускается на ARMv8 64

### ISSUE THREAD

**Issue by kostya4000** [danuk/shm#8]
Ошибка exec /entry.sh: exec format error
Ошибка на всех контейнерах кроме sql
root@instance-20220313-1016:/bin# docker ps
CONTAINER ID   IMAGE                  COMMAND                  CREATED             STATUS                          PORTS                 NAMES
0eab2c76e323   danuk/shm-admin:0.2    "/entry.sh"              About an hour ago   Restarting (1) 35 seconds ago                         shm_admin_1
b1c3e339c7b7   danuk/shm-client:0.2   "/entry.sh"              About an hour ago   Restarting (1) 36 seconds ago                         shm_client_1
6d620cf87521   danuk/shm-api:0.2      "/docker-entrypoint.…"   About an hour ago   Restarting (1) 37 seconds ago                         shm_api_1
7adc8ad258de   danuk/shm-core:0.2     "/entry.sh"              About an hour ago   Restarting (1) 40 seconds ago                         shm_spool_1
74a5de8f0177   danuk/shm-core:0.2     "/entry.sh"              About an hour ago   Restarting (1) 38 seconds ago                         shm_core_1
9556b6a982b7   mysql:8.0              "docker-entrypoint.s…"   About an hour ago   Up 25 minutes (healthy)         3306/tcp, 33060/tcp   shm_mysql_1

**Comment by it2ip** [comment]
Не запускается потому что нет сборки образов под ARM64. Если автор соберет образы под ARM64 то будет работать или откроет репозиторий shm-api. Я сбилдил shm-core, shm-client, shm-admin под ARM64 и они работают без ошибок, а вот shm-api такие же ошибки.

**Comment by danuk** [comment]
Проблем с запуском на ARM нет. Кроме того, разработка SHM осуществляется именно на ARM (MacBook M1).

Публиковать имаджы для ARM смысла не вижу, так как это может понадобится только для разработки или для тестирования, но вы всегда можете собрать проект самостоятельно, следуя этим инструкциями: https://docs.myshm.ru/docs/contribution/develop/
